export enum FecDataType {
    number = "number",
    string = "string",
    boolean = "boolean",
    function = "function",
    object = "object",
    ellipsisObject = "ellipsisObject",
    null = "null",
    array = "array",
    undefined = "undefined",
    key = "key",
    row = "row",
    getter = "getter",
    protectKey = "protectKey",
    br = "br",
    symbol = "symbol",
}
